#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}

function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'Failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	exit 1
  fi
  echo
  echo 'Finished' $1
  echo
	echo '***'
	echo '***'
	echo '***'
}

do_one inlist_create planet_create.mod
do_one inlist_evolve planet_evolve.mod
do_one inlist_evolve_grains planet_evolve_grains.mod
do_one inlist_evolve_clouds planet_evolve_clouds.mod
do_one inlist_evolve_window planet_evolve_window.mod
do_one inlist_evolve_delayed planet_evolve_delayed.mod
