#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_relax_composition_header planet_relaxed_composition.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

