#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_create_header planet_create.mod
do_one inlist_relax_composition planet_relax_composition.mod
do_one inlist_evolve_header planet_evolve.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

