#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}

function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'Failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	exit 1
  fi
  echo
  echo 'Finished' $1
  echo
	echo '***'
	echo '***'
	echo '***'
	echo
}


do_one inlist_create planet_create.mod
do_one inlist_evolve_z1 planet_evolve_z1.mod
do_one inlist_evolve_z2 planet_evolve_z2.mod
